### ISSUE TITLE
[1.0.1] CTD on opening commodities board

### ISSUE THREAD

**Issue by Anrock** [jaghaimo/stelnet#50]
Just updated stelnet, loaded my prev. save and tried to access commodities board.

Game crashed with "Fatal: null".

Here's stacktrace from starsector.log:
```
26425 [Thread-4] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException
java.lang.NullPointerException
	at stelnet.commodity.market.price.SupplyPrice.<init>(SupplyPrice.java:14)
	at stelnet.commodity.market.BuyMarketFactory.<init>(BuyMarketFactory.java:21)
	at stelnet.commodity.market.MarketRepository.<init>(MarketRepository.java:15)
	at stelnet.commodity.view.TableViewFactory.createTableContent(TableViewFactory.java:41)
	at stelnet.commodity.view.TableViewFactory.createContainer(TableViewFactory.java:27)
	at stelnet.commodity.CommodityBoard.getRenderables(CommodityBoard.java:68)
	at stelnet.ui.RenderableIntel.createLargeDescription(RenderableIntel.java:49)
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.Ò00000(Unknown Source)
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.actionPerformed(Unknown Source)
	at com.fs.starfarer.ui.newnew.buttonPressed(Unknown Source)
	at com.fs.starfarer.ui.oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Ò00000(Unknown Source)
	at com.fs.starfarer.ui.oooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.processInput(Unknown Source)
	at com.fs.starfarer.ui.newnew.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.Oo0o$Oo.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Oo0o.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.campaign.comms.v2.EventsPanel.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.campaign.comms.OOoO.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.class.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Oo0O.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.newui.o0oO.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.ui.oO00.dispatchEventsToChildren(Unknown Source)
	at com.fs.starfarer.ui.oO00.processInputImpl(Unknown Source)
	at com.fs.starfarer.ui.Q.processInput(Unknown Source)
	at com.fs.starfarer.campaign.CampaignState.processInput(Unknown Source)
	at com.fs.starfarer.BaseGameState.traverse(Unknown Source)
	at com.fs.state.AppDriver.begin(Unknown Source)
	at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
	at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Full [starsector.log](https://gist.githubusercontent.com/Anrock/a794aea604734aee302272ba58d49a46/raw/90016abbbd14a48cb15ac37f819d0ab56d2f6d1d/gistfile1.txt)

**Comment by jaghaimo** [comment]
Hi. Did you uninstall using previous version? Pre1 and pre2 has uninstall
versions and in pre3 you need to set an uninstallMod flag to true
(data/config/settings.json).

**Comment by Anrock** [comment]
No, I didn't. There wasn't a warning about save incompatibility, so I assumed saves are compatible.

Rolling back pre3 and uninstalling it with uninstallMod and then installing 1.0.1 worked, no CTDs.
