### ISSUE TITLE
Crash on load 

### ISSUE THREAD

**Issue by Makuru-DD** [jaghaimo/stelnet#89]
im using an aur package and it probably ones to save in an restricted location

possible fixes:
make it to only give an error message or add redundant save location like the mod directory

error code
 97929 [Thread-4] ERROR com.fs.starfarer.combat.CombatMain  - java.io.FileNotFoundException: stelnet.log (Keine Berechtigung)

**Comment by Makuru-DD** [comment]
i did and now it starts, thanks for the help

**Comment by jaghaimo** [comment]
Fixed in #90. @Makuru-DD could you test it if I gave you a build?

**Comment by Makuru-DD** [comment]
ok, how do i build the mod?

**Comment by jaghaimo** [comment]
You don't. Here's the build : [stelnet-2.6.1-rc2.zip](https://github.com/jaghaimo/stelnet/files/8878083/stelnet-2.6.1-rc2.zip)

**Comment by Makuru-DD** [comment]
jup its doing it's job

> 12414 [Thread-4] ERROR stelnet.util.Reporter  - Could not write to file
 java.io.FileNotFoundException: stelnet.log (Keine Berechtigung)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at java.io.PrintWriter.<init>(PrintWriter.java:184)
        at stelnet.util.Reporter.generate(Reporter.java:14)
        at stelnet.StelnetMod.onApplicationLoad(StelnetMod.java:31)
        at com.fs.starfarer.loading.ResourceLoaderState.init(Unknown Source)
        at com.fs.state.AppDriver.begin(Unknown Source)
        at com.fs.starfarer.combat.CombatMain.main(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher.o00000(Unknown Source)
        at com.fs.starfarer.StarfarerLauncher$1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)
